if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

 BiocManager::install("QuasR")
 BiocManager::install("Rsubread")
 BiocManager::install("edgeR")
 BiocManager::install("DESeq2")
 install.packages("ggplot2")
 install.packages("grid")
 install.packages("gridExtra")
 install.packages("plotrix")
 install.packages("tidyverse")
 install.packages("dplyr")
 
 install.packages("gWidgets2")
 install.packages("gWidgets2RGtk2")
 install.packages("cairoDevice")
 install.packages("future")



options(guiToolkit="RGtk2")
library(gWidgets2)
library(gWidgets2RGtk2)
library(cairoDevice)
library(future)
library(QuasR)
library(Rsubread)
library(edgeR)
library(DESeq2)
library(ggplot2)
library(grid)
library(gridExtra)
library(plotrix)
library(tidyverse)
library(dplyr)
#plan(multiprocess)
plan(multicore)
